env:
  IMAGE: bandsintown/alpine

steps:
  - label: ":docker: Build and Push Alpine v${VERSION}"
    if: build.env("VERSION") != "NA"
    plugins:
      - docker-compose#v5.2.0:
          build: alpine
          push:
            - alpine:${IMAGE}:${VERSION}-${BUILDKITE_COMMIT:0:7}

  - wait

  - label: ":docker: Tag as latest and Push Alpine v${VERSION}"
    if: build.env("VERSION_IS_LATEST") == "yes"
    plugins:
      - docker-compose#v5.2.0:
          push:
            - alpine:${IMAGE}:${VERSION}
            - alpine:${IMAGE}:latest
